src: add missing sys/stat.h import
Fix build error in src/common_drm.c caused by missing sys/stat.h
include:

common_drm.c:1002:14: error: storage size of 'st' isn't known

Signed-off-by: Dennis Gilmore <dennis@ausil.us>
Signed-off-by: Russell King <rmk@arm.linux.org.uk> [edited commit message]